# Generated by Django 4.0.5 on 2022-06-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grill', '0002_comment_player_alter_player_team_alter_rating_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comment_text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
