# Generated by Django 4.0.5 on 2022-06-21 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grill', '0003_rating_comment_text_alter_rating_rate_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='match',
        ),
        migrations.AddField(
            model_name='player',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match', to='grill.match'),
        ),
    ]
