# Generated by Django 4.0.5 on 2022-06-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grill', '0005_team_match_alter_player_team_alter_rating_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.RemoveField(
            model_name='player',
            name='match',
        ),
        migrations.AddField(
            model_name='player',
            name='match',
            field=models.ManyToManyField(to='grill.match'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
