# Generated by Django 4.0.5 on 2022-06-25 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grill', '0006_remove_player_team_remove_player_match_player_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match', to='grill.match'),
        ),
    ]
