# Generated by Django 4.0.5 on 2022-06-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grill', '0007_rating_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
