# Generated by Django 4.0.5 on 2022-07-02 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grill', '0008_alter_rating_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='grill.match'),
        ),
    ]
