# Generated by Django 4.0.5 on 2022-07-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grill', '0009_alter_rating_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
