# Generated by Django 4.0.5 on 2022-07-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grill', '0011_rating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='match',
        ),
        migrations.AddField(
            model_name='match',
            name='player',
            field=models.ManyToManyField(to='grill.player'),
        ),
    ]
